CREATE DATABASE IF NOT EXISTS moms_db;
USE moms_db;

-- =====================================================
-- MASTER ROLE
-- =====================================================
CREATE TABLE MM_MAS_ROLE (
    ROLE_ID VARCHAR(100) PRIMARY KEY,
    ROLE_NAME VARCHAR(100) NOT NULL,
    ROLE_DESCRIPTION VARCHAR(255),
    ROLE_STATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE'
);

-- =====================================================
-- USER LOGIN
-- =====================================================
CREATE TABLE MM_USER_LOGIN (
    USER_ID VARCHAR(100) PRIMARY KEY,
    USER_ROLE_ID VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(150) NOT NULL UNIQUE,
    USER_MOBILE VARCHAR(15) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    USER_STATUS ENUM('ACTIVE','BLOCKED') DEFAULT 'ACTIVE',
    USER_LAST_LOGIN DATETIME,
    USER_LAST_LOGOUT DATETIME,
    USER_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_USER_ROLE
    FOREIGN KEY (USER_ROLE_ID)
    REFERENCES MM_MAS_ROLE(ROLE_ID)
);

-- =====================================================
-- ADMIN DETAILS
-- =====================================================
CREATE TABLE MM_ADMIN (
    ADMIN_ID VARCHAR(100) PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    ADMIN_NAME VARCHAR(150) NOT NULL,
    ADMIN_IMAGE VARCHAR(255),
    ADMIN_ADDRESS TEXT,
    ADMIN_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_ADMIN_USER
    FOREIGN KEY (USER_ID)
    REFERENCES MM_USER_LOGIN(USER_ID)
);

-- =====================================================
-- CUSTOMER DETAILS
-- =====================================================
CREATE TABLE MM_CUSTOMER (
    CUSTOMER_ID VARCHAR(100) PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    CUSTOMER_NAME VARCHAR(150) NOT NULL,
    CUSTOMER_GENDER VARCHAR(20),
    CUSTOMER_DOB DATE,
    CUSTOMER_IMAGE VARCHAR(255),
    CUSTOMER_ADDRESS TEXT,
    CUSTOMER_CITY VARCHAR(100),
    CUSTOMER_STATE VARCHAR(100),
    CUSTOMER_PINCODE VARCHAR(10),
    CUSTOMER_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_CUSTOMER_USER
    FOREIGN KEY (USER_ID)
    REFERENCES MM_USER_LOGIN(USER_ID)
);

-- =====================================================
-- CUSTOMER ADDRESS
-- =====================================================
CREATE TABLE MM_CUSTOMER_ADDRESS (
    ADDRESS_ID VARCHAR(100) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(100) NOT NULL,
    FULL_ADDRESS TEXT,
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    PINCODE VARCHAR(10),
    COUNTRY VARCHAR(100),

    CONSTRAINT FK_ADDRESS_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES MM_CUSTOMER(CUSTOMER_ID)
);

-- =====================================================
-- CATEGORY MASTER
-- =====================================================
CREATE TABLE MM_MAS_CATEGORY (
    CATEGORY_ID VARCHAR(100) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    CATEGORY_DESCRIPTION VARCHAR(255),
    CATEGORY_STATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE'
);

-- =====================================================
-- BRAND MASTER
-- =====================================================
CREATE TABLE MM_MAS_BRAND (
    BRAND_ID VARCHAR(100) PRIMARY KEY,
    BRAND_NAME VARCHAR(100) NOT NULL,
    BRAND_STATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE'
);

-- =====================================================
-- PRODUCT MASTER
-- =====================================================
CREATE TABLE MM_PRODUCT (
    PRODUCT_ID VARCHAR(100) PRIMARY KEY,
    CATEGORY_ID VARCHAR(100) NOT NULL,
    BRAND_ID VARCHAR(100) NOT NULL,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    PRODUCT_DESCRIPTION TEXT,
    PRODUCT_PRICE DECIMAL(10,2) NOT NULL,
    PRODUCT_DISCOUNT DECIMAL(10,2) DEFAULT 0.00,
    PRODUCT_SELL_PRICE DECIMAL(10,2) DEFAULT 0.00,
    PRODUCT_STOCK INT DEFAULT 0,
    PRODUCT_IMAGE VARCHAR(255),
    PRODUCT_STATUS ENUM('ACTIVE','OUT OF STOCK') DEFAULT 'ACTIVE',
    PRODUCT_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_PRODUCT_CATEGORY
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES MM_MAS_CATEGORY(CATEGORY_ID),

    CONSTRAINT FK_PRODUCT_BRAND
    FOREIGN KEY (BRAND_ID)
    REFERENCES MM_MAS_BRAND(BRAND_ID)
);

-- =====================================================
-- CART
-- =====================================================
CREATE TABLE MM_CART (
    CART_ID VARCHAR(100) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(100) NOT NULL,
    PRODUCT_ID VARCHAR(100) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    ADDED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_CART_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES MM_CUSTOMER(CUSTOMER_ID),

    CONSTRAINT FK_CART_PRODUCT
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES MM_PRODUCT(PRODUCT_ID)
);

-- =====================================================
-- ORDER MASTER
-- =====================================================
CREATE TABLE MM_ORDER (
    ORDER_ID VARCHAR(100) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(100) NOT NULL,
    ORDER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,
    ORDER_STATUS ENUM(
        'PENDING',
        'CONFIRMED',
        'PROCESSING',
        'SHIPPED',
        'DELIVERED',
        'CANCELLED'
    ) DEFAULT 'PENDING',

    CONSTRAINT FK_ORDER_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES MM_CUSTOMER(CUSTOMER_ID)
);

-- =====================================================
-- ORDER DETAILS
-- =====================================================
CREATE TABLE MM_ORDER_DETAILS (
    ORDER_DETAILS_ID VARCHAR(100) PRIMARY KEY,
    ORDER_ID VARCHAR(100) NOT NULL,
    PRODUCT_ID VARCHAR(100) NOT NULL,
    PRODUCT_PRICE DECIMAL(10,2),
    QUANTITY INT,
    TOTAL_PRICE DECIMAL(10,2),

    CONSTRAINT FK_ORDERDETAIL_ORDER
    FOREIGN KEY (ORDER_ID)
    REFERENCES MM_ORDER(ORDER_ID),

    CONSTRAINT FK_ORDERDETAIL_PRODUCT
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES MM_PRODUCT(PRODUCT_ID)
);

-- =====================================================
-- PAYMENT
-- =====================================================
CREATE TABLE MM_PAYMENT (
    PAYMENT_ID VARCHAR(100) PRIMARY KEY,
    ORDER_ID VARCHAR(100) NOT NULL,
    PAYMENT_METHOD VARCHAR(50),
    PAYMENT_AMOUNT DECIMAL(10,2),
    PAYMENT_STATUS ENUM(
        'PENDING',
        'SUCCESS',
        'FAILED'
    ) DEFAULT 'PENDING',
    PAYMENT_DATE DATETIME,

    CONSTRAINT FK_PAYMENT_ORDER
    FOREIGN KEY (ORDER_ID)
    REFERENCES MM_ORDER(ORDER_ID)
);

-- =====================================================
-- ORDER STATUS HISTORY
-- =====================================================
CREATE TABLE MM_ORDER_STATUS (
    STATUS_ID VARCHAR(100) PRIMARY KEY,
    ORDER_ID VARCHAR(100) NOT NULL,
    STATUS_NAME VARCHAR(100),
    STATUS_DATE DATETIME,
    REMARKS TEXT,

    CONSTRAINT FK_STATUS_ORDER
    FOREIGN KEY (ORDER_ID)
    REFERENCES MM_ORDER(ORDER_ID)
);

-- =====================================================
-- PRODUCT REVIEW
-- =====================================================
CREATE TABLE MM_PRODUCT_REVIEW (
    REVIEW_ID VARCHAR(100) PRIMARY KEY,
    PRODUCT_ID VARCHAR(100) NOT NULL,
    CUSTOMER_ID VARCHAR(100) NOT NULL,
    RATING INT,
    REVIEW TEXT,
    REVIEW_DATE DATETIME,

    CONSTRAINT FK_REVIEW_PRODUCT
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES MM_PRODUCT(PRODUCT_ID),

    CONSTRAINT FK_REVIEW_CUSTOMER
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES MM_CUSTOMER(CUSTOMER_ID)
);

-- =====================================================
-- CONTACT US
-- =====================================================
CREATE TABLE MM_CONTACT_US (
    CONTACT_ID VARCHAR(100) PRIMARY KEY,
    NAME VARCHAR(150),
    EMAIL VARCHAR(150),
    MOBILE VARCHAR(15),
    SUBJECT VARCHAR(200),
    MESSAGE TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
